console.log("HEY 1")
console.log("HEY 2")
setTimeout(function(){
    console.log("HEY 3")
} , 0.001 )
console.log("HEY 4")
console.log("HEY 5")
console.log("HEY 6")
console.log("HEY 7")
console.log("HEY 8")
console.log("HEY 9")
console.log("HEY 10")
console.log("HEY 11")
console.log("HEY 12")
console.log("HEY 13")
console.log("HEY 13")
